version: '3.9'

services:
  app:
    container_name: app_container
    tty: true
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - slobbo-api
    networks:
      - whatisthis

  slobbo-api:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - whatisthis

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - slobbo-api
    ports:
      - "5050:80"
    networks:
      - whatisthis
    restart: unless-stopped

volumes:
  api:
  database_postgres:

# Networks to be created to facilitate communication between containers
networks:
  whatisthis:
    driver: bridge