apiVersion: apps/v1
kind: Deployment
metadata:
  name: slobbo-backend-deployment
  namespace: slobbo
  labels:
    app: slobbo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slobbo-backend
  template:
    metadata:
      labels:
        app: slobbo-backend
    spec:
      containers:
      - name: slobbo-backend
        image: slobbo/slobbo-api:1.0.0
        imagePullPolicy: IfNotPresent
        resources:                                
          limits:                                 
            cpu: 900m
          requests:                               
            cpu: 500m     
        ports:
          - name: http
            containerPort: 8080
        envFrom:
          - secretRef:
              name: postgres-secret