apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    name: slobbo
spec:
  storageClassName: efs-sc
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-043d8d1ff9f2a79b6