apiVersion: v1
kind: PersistentVolumeClaim 
metadata:                                    
  name: postgres-pvc
  namespace: slobbo
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: slobbo    
  